# Generated by Django 5.1.5 on 2025-02-02 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conference',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conference',
            name='join_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='conference',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
