# Generated by Django 5.1.5 on 2025-02-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='member',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='member',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events_images/'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
