spring:
  profiles.active: local

  jpa:
    open-in-view: false

secret:
  jwt:
    secret-key: ${JWT_SECRET_KEY:secretsecretsecretsecretsecretsecretsecretsec}
    expire-time: ${JWT_EXPIRE_TIME:31536000000}
  aws:
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME:aaaa}
    region: ${AWS_REGION:aaaa}
    credentials:
      access-key: ${AWS_ACCESS_KEY:aaaa}
      secret-key: ${AWS_SECRET_KEY:aaaa}
