spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate.format_sql: true

secret:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expire-time: ${JWT_EXPIRE_TIME}
  aws:
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
