spring:
  profiles.active: local

  jpa:
    open-in-view: false

secret:
  jwt:
    secret-key: ${JWT_SECRET_KEY:secretsecretsecretsecretsecretsecretsecretsec}
    expire-time: ${JWT_EXPIRE_TIME:31536000000}
